steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "Building with branch: $BRANCH_NAME"
      echo "***********************"

- id: 'tf destroy dev'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd environments/dev
      terraform init
      terraform destroy -auto-approve

- id: 'tf destroy prd'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd environments/prd
      terraform init
      terraform destroy -auto-approve
